### ISSUE TITLE
Mermaid formats for preview

### ISSUE THREAD

**Issue by vozkych** [searKing/preview-vscode#1]
Which Mermaid formats are supported to preview?

I have found only plain text file with .mermaid extension. [Official file extension .mmd](https://github.com/knsv/mermaid/issues/147) does not work.

Would be possible to add suport for Markdown fenced code?
`` `````mermaid

**Comment by searKing** [comment]
.mmd is recognized as mermaid extension now, thank you for your adverse！

**Comment by searKing** [comment]
It's possible to add support for Markdown fenced code "```mermaid";One way is to convert markdown to html with a hack, as I have done to preview the reStructedText in this extension.
But currently, I use native markdown preview in vscode to preview the markdown files,which will be always following the latest vscode, and keep the user experience the same as official vscode Markdown Preview.

**Comment by vozkych** [comment]
Thank you for update! Regarding the markdown fenced code, I understand the issue. Maybe one day, when VSCode extension api will be contain some callback support for the markdown blocks, this would be possible..
