### ISSUE TITLE
Issue with hotkeys

### ISSUE THREAD

**Issue by hellofedorov** [searKing/preview-vscode#11]
I use VSC on MacOS 10.11
For opening Preview to the side, I use **⌘K V** and can't use **⌃K V** 
but for opening context menu (where I can determine a type of preview) I only can use **⌃K V** and can't use **⌘K V** 
Can you set up a single hotkey for making it features?

**Comment by searKing** [comment]
I have set hotkeys as ⌘K V and ⌘+Shift+V for Mac right away.
But I have my MacBook installed on an pure Ubuntu system only, so I am so grateful if you can test whether these keys can work on your MacBook.
Upgrade the Preview to v1.1.2 at least to have a try!

**Comment by hellofedorov** [comment]
All works! Thanks!
