### ISSUE TITLE
Support task lists in Markdown

### ISSUE THREAD

**Issue by hellofedorov** [searKing/preview-vscode#12]
Why your Preview doesn't support task lists? 
http://take.ms/fee0H

**Comment by searKing** [comment]
Preview V1.3.2 has support the task lists, have a try!
There is an example below:
# markdown content
```html
#### GFM task list
- [x] GFM task list 1
- [x] GFM task list 2
- [ ] GFM task list 3
    - [ ] GFM task list 3-1
    - [ ] GFM task list 3-2
    - [ ] GFM task list 3-3
- [ ] GFM task list 4
    - [ ] GFM task list 4-1
    - [ ] GFM task list 4-2
```
# markdown previewer
#### GFM task list
- [x] GFM task list 1
- [x] GFM task list 2
- [ ] GFM task list 3
    - [ ] GFM task list 3-1
    - [ ] GFM task list 3-2
    - [ ] GFM task list 3-3
- [ ] GFM task list 4
    - [ ] GFM task list 4-1
    - [ ] GFM task list 4-2
