### ISSUE TITLE
preview local image in frame ?

### ISSUE THREAD

**Issue by jonlepage** [searKing/preview-vscode#13]
**Hi friend,** 
I'm desperately looking for a plugin, which will allow me to simply visualize a reference to an image.

I have to build a huge database.
Similar to Json, but in JS.
Do you have an idea if a plugin that would allow me to visualize a local image in a frames exists?

I took the time to make a small image to show my need.
I will be really happy if, through your experience, you will have a small plugin that will allow this feature.
I would like to see a local image when my mouse passes over a link that references a local image.

Preview
http://imgbox.com/sHLBF4kF
![vsc-plugin-iomage-preview](https://cloud.githubusercontent.com/assets/24865815/24588940/d56b66b8-179f-11e7-8fd3-6116607f3f51.jpg)

Do you have an idea if your plugin can do something similar, or know you a plugin that could have this feature?

Thank you very much for your help.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/searKing/preview-vscode/issues/13#issue-218775770

@jonlepage, have you tried converting those Windows paths into `file:` URIs? At the least, they'll be easily clickable, so you'll be half-way there.

**Comment by jonlepage** [comment]
> > [#13 (comment)](https://github.com/searKing/preview-vscode/issues/13#issue-218775770)
> 
> @jonlepage, have you tried converting those Windows paths into `file:` URIs? [1](#user-content-fn-1-143db3b5a93d15262db2c44fdfaaffa3) At the least, they'll be easily clickable, so you'll be half-way there.
> 
> ## Footnotes
> 1. [`stackoverflow.com/revisions/44692962/3`](https://stackoverflow.com/revisions/44692962/3#:~:text=So%20if%20we%20were%20to,file:///c:/Folder/test.txt) [↩](#user-content-fnref-1-143db3b5a93d15262db2c44fdfaaffa3)

this one do the magik
https://github.com/kisstkondoros/gutter-preview

![image](https://github.com/user-attachments/assets/b0738edc-335f-4709-9cac-69cef00d4059)
