### ISSUE TITLE
Preview not working for .pug

### ISSUE THREAD

**Issue by peterdanis** [searKing/preview-vscode#18]
Preview is not working for .pug files.
![image](https://user-images.githubusercontent.com/26599181/29359267-46ad5f86-827e-11e7-9871-e4242ff75a6c.png)

**Comment by searKing** [comment]
This feature will be available in the next release, thanks!

**Comment by searKing** [comment]
1. Preview V1.3.0 has support  the pug template [.pug], have a try!
2. the template can be supported also!
3. There is an example below:
```code
// declare variables here
- var data='<strong> a luck day <strong/>'
h1 HelloWorld
p Tody is #{data}!
```

**Comment by RocMark** [comment]
umm still not working QQ any setting should be made?
