### ISSUE TITLE
I can not use Markdown preview

### ISSUE THREAD

**Issue by Tekbr** [searKing/preview-vscode#2]
- VSCode Version: 1.3.0-insider
- OS Version: Windows 10

-- Sorry for the English, I used Google Translator --

I can not use Markdown preview, after installing the extension. It does not work with the preview of the extension, or with the preview of native VSCode - Insider.

"Ctrl + k v " or "Command Palette" does not work.

**Comment by Tekbr** [comment]
UPDATE: the native preview Markdown VSCode - Insider works in the Command Palette

**Comment by searKing** [comment]
I have tested it and the bug is caused by the native command is different between the  VSCode Version: 1.3.0-insider and 1.2.0-stable. I'll fix it and thank you for your feedback!

**Comment by searKing** [comment]
It's fixed, Try it !

**Comment by Tekbr** [comment]
Thanks for the extension. Worked perfectly. Sorry for being slow to respond.
