### ISSUE TITLE
reStructuredText Preview does not find rst2html.py

### ISSUE THREAD

**Issue by Lorendin** [searKing/preview-vscode#20]
I am on debian stretch and have the python docutils installed. The extension is searching for rst2html.py but on my system it is named just rst2html without the .py extension.

By the way, the error message has a typo: doctuils->docutils

Thanks for providing the extension

**Comment by anandtrex** [comment]
Similar problem here. Would be nice if there was a config option to set the path of rst2html.

**Comment by osya** [comment]
I solved it by associating .py extension with Python interpreter. I'v done it via Windows Explorer - Open with ..., the select "Python" and check the box "Always use this app to open ... files". Now .rst files can be previewed in VS Code via this extension

**Comment by darkvertex** [comment]
Having this problem too.

**Comment by darkvertex** [comment]
Also, when it says "rst2html" is it referring to "[rst2html5](https://pypi.org/project/rst2html5/)" or an earlier version?

**Comment by searKing** [comment]
Make sure your docutils is installed sucessfully.
```bash
which rst2html.py
/usr/local/bin/rst2html.py
```

**Comment by abetaev** [comment]
in debian gnu/linux when you install python-docutils ``/usr/bin/rst2html`` is what you are calling ``/usr/local/bin/rst2html.py``. and there are a lot of more ways where ``rst2html`` can be located or which programming language was used to implement it.
problem is that i was not able to find a way to configure location of such program. here i see an issue for me and small feature with at least nice to have priority.

the workaround is obvious and costs nothing, but still...

**Comment by rgammans** [comment]
This is a problem as docutils is install properly in these cases, as in the correct path (eg /usr/bin; see the FSSTND) as a  working command named 'rst2html'. It is only really on windows where it called 'rst2html.py'

I strongly feel this issue was closed without understanding the way packages are installed and the way python is normally used on linux (and other unix platforms), and should be re-opened.

**Comment by n3storm** [comment]
Debian 8, docutils from package, both paths are available /usr/bin/rst2html and /usr/local/bin/rst2html.py

**Comment by searKing** [comment]
> This is a problem as docutils is install properly in these cases, as in the correct path (eg /usr/bin; see the FSSTND) as a working command named 'rst2html'. It is only really on windows where it called 'rst2html.py'
> 
> I strongly feel this issue was closed without understanding the way packages are installed and the way python is normally used on linux (and other unix platforms), and should be re-opened.

You are right, I have not test it on Debian and there is something different from Ubuntu or CentOS, see [rst2html is usually installed as rst2html.py](https://github.com/aria2/aria2/issues/91).

**Comment by searKing** [comment]
It's fixed after V2.0.3, the new category is rst2html5.py -> rst2html5 -> rst2html.py -> rst2html.
