### ISSUE TITLE
Preview doesn't respect vertical-align correctly.

### ISSUE THREAD

**Issue by ClairelyClaire** [searKing/preview-vscode#21]
Example:

    <style>
        DIV {
            height: 100px;
            width: 200px;
            display: table-cell;
            vertical-align: middle;
        }
    </style>
    <div>This should be vertically centered.</div>

**Comment by searKing** [comment]
I did not reproduce this bug. It works well as my VSCODE is 1.25.1 and Preview is 1.4.4.
