### ISSUE TITLE
CMD+K does not clear integrated terminal if Preview is enabled

### ISSUE THREAD

**Issue by alwazzan** [searKing/preview-vscode#22]
The default keybinding `cmd+k` to clear the integrated terminal when the terminal is in focus does not work as expected if Preview extension is enabled. 

To reproduce:

1. Enable Preview
2. Open integrated terminal
3. Type a couple of commands
4. Press `cmd+k`
5. "(cmd+K) was pressed. Waiting for second key of cord..." shows in the status bar.

Disabling Preview fixes the issue. 

* Preview Version: 1.4.2
* VSCode Version: 1.18.1
* OS Version: MacOS Sierra

**Comment by searKing** [comment]
Thanks a lot，this BUG will be fixed by v1.4.4 at least
