### ISSUE TITLE
Preview won't find pygments when running python bin from virtualenv

### ISSUE THREAD

**Issue by heron182** [searKing/preview-vscode#23]
When running python from a virtualenv, Preview will complain it can't find pygments for code-blocks highlights, even if pygments is actually installed in the virtualenv packages.
Funny things is that it will throw me a docutils error if i don't install it in my virtualenv folder.

**Comment by searKing** [comment]
1. Preview will try docutils first to preview the ReStructured Text  more accurately. If doctuils is not installed or called failed, we use a simple preview instead.
2. I have remove the unnecessary debug log after this version [>=1.4.5]
