### ISSUE TITLE
Bad code highlighting

### ISSUE THREAD

**Issue by mingrammer** [searKing/preview-vscode#24]
I installed preview to do editing the technical rst documentation on vscode. However, the rendered code block is too hard to see .. like this:

![image](https://user-images.githubusercontent.com/6178510/36726301-9638e7a6-1bfc-11e8-9ff6-8026d18120e6.png)

How about using other highlighting format?

**Comment by mingrammer** [comment]
I think you can generate `good` (which means that easy to see) code highlighter with pygment, then locate it to `static` directory and use it during run the **docutils** command

**Comment by takeontom** [comment]
Would be ideal if styling could somehow be generated from the colour scheme currently being used in VS Code.

**Comment by Shihta** [comment]
@mingrammer 
Could you show some simple steps that how to do it?
Or how to modify the source to do it?

**Comment by searKing** [comment]
You can change the default dark theme, as issues28: [How to change the background color of code block?](https://github.com/searKing/preview-vscode/issues/28)
