### ISSUE TITLE
Spaces in paths

### ISSUE THREAD

**Issue by micfort** [searKing/preview-vscode#25]
When a file with spaces in the path, it is by the command line seen as multiple arguments by docutils.
If a space is added to the path it only gives the following message:
> try rst2html of doctutils failed, please check python and doctuils environment, we use a simple preview instead ^-)

This can easily be solved by the following change

For example in docutilsUtil.ts
`return ShellUtil.execPromisLike([
            command,
            fileName
        ].join(" "));`

should be changed into 

`return ShellUtil.execPromisLike([
            command,
            "\""+fileName+"\""
        ].join(" "));`

I do not know where this change has to occur for everything to work correctly

**Comment by searKing** [comment]
Thanks a lot，this bug will be merge by v1.4.3 at least
