### ISSUE TITLE
Why ctrl-k ?

### ISSUE THREAD

**Issue by zwoop** [searKing/preview-vscode#26]
Is there any way to make this extension not bind <ctrl>-k  for the preview? This messes with the existing (default) ctrl-k (delete to end of line). Since <cmd>-k is used for this, it'd be really nice on a Mac at least to not have it hijack ctrl-k as well.

Any ideas?

**Comment by searKing** [comment]
You can change the key mapping to what you want, The steps to change are as follows:
![keymap](https://user-images.githubusercontent.com/4208726/43679928-1c70b4b2-9861-11e8-80fe-f5058e0f3b73.gif)

**Comment by zwoop** [comment]
Pretty sure I tried this, but I'll try it again. It seemed to me that ctrl-k was hardcoded, but possible I'm wrong :).

**Comment by searKing** [comment]
It worked for me :). I have tried "ctrl+k y" instead of "ctrl+k v". My currrent development platform is  Ubuntu18.04.
