### ISSUE TITLE
might be a typo doctuils ( instead of docutils )

### ISSUE THREAD

**Issue by usta** [searKing/preview-vscode#27]
https://github.com/searKing/preview-vscode/blob/master/src/manager/reStructuredTextDocumentContentManager.ts#L86

and

https://github.com/searKing/preview-vscode/blob/master/src/manager/reStructuredTextDocumentContentManager.ts#L88

and

https://github.com/searKing/preview-vscode/blob/master/README.md#L36

has same typo , instead of docutils it is written as doctuils

**Comment by searKing** [comment]
Thanks a lot，this typo will be fixed by v1.4.3 at least

**Comment by usta** [comment]
Hi, you have fixed only one place other typos ( '' doctuils '' ) are still exist in those files ( which i mentioned )

**Comment by searKing** [comment]
Thanks a lot，this typo will be fixed by v1.4.4 at least.
