### ISSUE TITLE
How to change the background color of code block?

### ISSUE THREAD

**Issue by Shihta** [searKing/preview-vscode#28]
It's hard to see clearly on the "code" block, as below:

![2018-05-25 11 22 47](https://user-images.githubusercontent.com/5186176/40524666-4d349f9a-600e-11e8-8bf1-aedb859e50a2.png)

How to change the background color of code block?

**Comment by searKing** [comment]
You can change the default theme of VSCODE
Launch Quick Open,

 Linux Ctrl + Shift + P
 macOS ⌘ + Shift + P
 Windows Ctrl + Shift + P
Type theme and choose Preferences: Color Theme, then select one of the Material Theme variant from the list. After the activation the theme will set the correct icons theme for you, based on your picked theme variant.
