### ISSUE TITLE
Toggle preview to side and normal preview does not work with RST

### ISSUE THREAD

**Issue by SalahAdDin** [searKing/preview-vscode#29]
I'm testing this extension ir order to can preview the `.rst` files, but although I can see files of the `markdown` type, the same thing does not happen with `reStructuredText` files:
![deepin-screen-recorder_code_20180803110145](https://user-images.githubusercontent.com/5034215/43631936-50a96b48-970d-11e8-922b-ae9f581edde4.gif)

My OS is Antergos Linux:
```batch
OS: Arch Linux
Kernel: x86_64 Linux 4.17.6-1-ARCH
Uptime: 15h 24m
Packages: 1434
Shell: zsh 5.5.1
Resolution: 1920x1080
DE: Deepin 15.6
WM: Deepin WM
WM Theme: Materia-light-compact
GTK Theme: Materia-light-compact [GTK2/3]
Icon Theme: Halo
CPU: Intel Core i7-4720HQ @ 8x 3.6GHz [64.0°C]
GPU: GeForce GTX 960M
RAM: 8452MiB / 15932MiB
```

And VSCode: 
```bash
Versión: 1.25.1
Confirmación: 1dfc5e557209371715f655691b1235b6b26a06be
Fecha: 2018-07-11T15:40:20.190Z
Electron: 1.7.12
Chrome: 58.0.3029.110
Node.js: 7.9.0
V8: 5.8.283.38
Arquitectura: x64
```

**Comment by include** [comment]
Same problem here.
I am using VSCode / Windows 10 / WSL.

I've installed pipenv so I set python path to pipenv --py
(something like: ~/.local/share/virtualenvs/z-tmp-Smv5tS8l/bin/python)

I would like to have such a simple tool to burn and preview rst files. 10x

**Comment by mobidyc** [comment]
same here
extension version  2.0.3
Fedora 30 fresh installed
work for .md file, nothing happens for .rst file.

**Comment by searKing** [comment]
Hi, Preview[2.1.0] is updated to use the latest API after VSCode[1.34.0], 
Upgrade the Preview to v2.1.0 at least to have a try!.
