### ISSUE TITLE
加粗里面有括号紧邻貌似不能被解析.

### ISSUE THREAD

**Issue by cclxpp123** [searKing/preview-vscode#39]
加粗里面有括号紧邻貌似不能被解析. 斜体也如此.
![image](https://user-images.githubusercontent.com/22320996/80968113-ff960500-8e49-11ea-9bf9-e120c420ac52.png)

![image](https://user-images.githubusercontent.com/22320996/80967720-649d2b00-8e49-11ea-9d13-80f19909daf0.png)

**Comment by searKing** [comment]
Same in Github and [Markdown-it](https://markdown-it.github.io/), you could use ```一<strong>二三</strong>四``` for *Bold* and  ```一<em>二三</em>四```
```一<strong>二三</strong>四``` :一<strong>二三</strong>四
```一<em>二三</em>四``` 一<em>二三</em>四
