### ISSUE TITLE
missing mermaid

### ISSUE THREAD

**Issue by tomdavidson** [searKing/preview-vscode#4]
Just trying preview. Is it suppose to render embedded mermaid diagrams or just mermaid files?

v 1.1.1 does not show the diagram embedded in markdown file.

**Comment by dudymas** [comment]
It looks like it only supports making mmd files for this.

That said, it looks like the mermaid version is rather old. If I try to use activate/deactivate in a sequenceDiagram, the rendering fails:

```
sequenceDiagram
    Alice->>+John: imma activate you
    John->>Alice: stahp
    deactivate John
```

That's a valid sequence Diagram, and it does not work with mmd previews

If, instead, I load up the dedicated mermaid preview app, it works just fine.

**Comment by JCzz** [comment]
I have same problem, no mermaid - but works in  mermaid preview.

**Comment by searKing** [comment]
It has been supported now, update to v1.1.4 at least
