### ISSUE TITLE
"Active editor doesn't show a HTML or Jade document - no properties to preview."

### ISSUE THREAD

**Issue by rbtcollins** [searKing/preview-vscode#40]
Use case viewing an HTML file built by rust-doc in a remote-SSH session. So there's no build-task configured (though I could do one I guess).

Anyhow, open index.html, open live preview, asks for file type, tell it HTML/Jade, get this error:
```
Active editor doesn't show a HTML or Jade document - no properties to preview.
```

Current vscode and preview-vscode.

**Comment by searKing** [comment]
Preview[2.3.2] is updated to use the Markdown API, Now works well if file name renamed with suffix '.jade' or '.pug'.
