### ISSUE TITLE
[request] Render CSS files

### ISSUE THREAD

**Issue by protiumx** [searKing/preview-vscode#41]
Hey guys, is there any way to have a html/pug file with relative css?
I have a pug file with this
```pug
link(rel="stylesheet", href="css/main.css", data-inline)
```
or 
```pug
style.
  include main.css
```
but the CSS is not being rendered or imported.
Thanks!

**Comment by jamiecarter7** [comment]
Yes, I downloaded this package specifically to do this. +1

**Comment by searKing** [comment]
Preview[2.3.2] is updated to use the Markdown API, external CSS supported.
+ HTML
```html
<link rel="stylesheet" href="css/main.css"  data-inline>
```

+ PUG
```pug
link(rel="stylesheet", href="css/main.css", data-inline)
```
+ PUG
```pug
style.include main.css
```
