### ISSUE TITLE
[request]: enable search like HTML preview + double click to go to line in source

### ISSUE THREAD

**Issue by MagTun** [searKing/preview-vscode#43]
It's great to have the same extension for multiple file support but it would be nice to be able to search in the preview pane like [the HTML preview extension does](https://github.com/tht13/html-preview-vscode).

Also it would be nice if I double click on a sentence on the preview pane to be redirected to the corresponding line in the original file. 

Thanks!

**Comment by searKing** [comment]
Preview[2.3.2] is updated to use the Markdown API, Now back to source as `'markdown.showSource'` is supported.
