### ISSUE TITLE
can't preview the raw jpg

### ISSUE THREAD

**Issue by WLswert** [searKing/preview-vscode#5]
HI !
I think this ext is amazing.but  I found  a litter bug , it can preview the original image from the local or internet  , when i  deal with the image like  using python zoom in or out ,it can't preview ,and tell me the can't  preview the binary file.but  I can  view the image  using the windows tools .

**Comment by searKing** [comment]
Can you describe your steps in detail? Such as how to deal with the image like using python zoom in or out ? I need some more details about how to use python zoom in or out.

**Comment by searKing** [comment]
Frozen to Date
