### ISSUE TITLE
Multiple preview menus

### ISSUE THREAD

**Issue by jsoref** [searKing/preview-vscode#57]
Issue Type: <b>Bug</b>

1. Right click a tab of a markdown file
2. See 3 preview items
3. Clicking one opens a preview pane
4. Clicking another closes the first preview pane
5. Clicking the last one opens an unrelated preview pane

https://user-images.githubusercontent.com/2119212/122399300-a9e6c400-cf48-11eb-9b25-591a965eaa9c.mov

Extension version: 2.2.5
VS Code version: Code 1.57.0 (b4c1bd0a9b03c749ea011b06c6d2676c8091a70c, 2021-06-09T17:22:31.215Z)
OS version: Darwin x64 20.5.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz (8 x 2500)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|5, 3, 3|
|Memory (System)|16.00GB (0.16GB free)|
|Process Argv|--crash-reporter-id 1fc67ee2-0174-4598-9f98-4537df0dd32c|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30311712
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255:30319631
vscorehov:30309549
vscod805cf:30301675

```

</details>

**Comment by searKing** [comment]
Hi, Preview[2.3.2] is updated to use the Markdown API, Now no more extra preview menus.
