### ISSUE TITLE
404 on attempting to launch in on web

### ISSUE THREAD

**Issue by JacksonKearl** [searKing/preview-vscode#63]
Hello from the VS Code team! 👋

Thanks for working on support for web sessions of vscode! When I try to install this on github.dev, I see an error in activation due to not being able to find https://searking.vscode-unpkg.net/searKing/preview-vscode/2.2.4/extension/dist/browser/extension.js, which indeed does not exist. I see that you have webpack config for web set up so it's not clear to me what isn't working correctly here.

**Comment by searKing** [comment]
Preview[2.3.2] is updated to use the Markdown API, and web is supported.
