### ISSUE TITLE
Incorrect Markdown preview with searking.preview-vscode

### ISSUE THREAD

**Issue by FalkTannhaeuser** [searKing/preview-vscode#64]
Issue Type: <b>Bug</b>

Math formulas were not rendered and syntax coloring was not applied to code blocks in Markdown preview (Ctrl-Shift-V). Extension bisect identified "searking.preview-vscode" as cause of the problem.

Extension version: 2.2.5
VS Code version: Code 1.64.0 (5554b12acf27056905806867f251c859323ff7e9, 2022-02-03T04:22:20.678Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9850H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.79GB (6.09GB free)|
|Process Argv|--crash-reporter-id 3030ca11-c827-4aac-8a14-3609c3c2043f|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392cf:30425750
pythontb:30283811
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30433059
pythonvs932:30410667
wslgetstartedc:30433508
vs360cf:30404996
vsclayoutctrt:30425946
vsrem710:30416614

```

</details>

**Comment by searKing** [comment]
Preview[2.3.2] is updated to use the Markdown API, Now [math](https://github.com/microsoft/vscode-markdown-it-katex/tree/main?tab=readme-ov-file#examples) is supported.
