### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by yoleanin** [searKing/preview-vscode#68]
- Issue Type: `Performance`
- Extension Name: `preview-vscode`
- Extension Version: `2.2.5`
- OS Version: `Windows_NT x64 10.0.19044`
- VS Code version: `1.69.2`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`file:///c%3A/Users/Andrea/AppData/Local/Temp/searKing.preview-vscode-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by searKing** [comment]
Preview[2.3.2] is updated to use the Markdown API, no more extra text editor and document provider.
