### ISSUE TITLE
Preview does not scroll with editor

### ISSUE THREAD

**Issue by SigmaticDev** [searKing/preview-vscode#74]
I just installed the extension and completed the following steps:
- Opened an HTML file
- Opened the Preview in a new tab
- Split the view to see two tabs at once
- Dragged the Preview tab to the other view so both Editor and Preview are visible at once

In the extension's settings both of the following settings are toggled true:
- Preview > Preview: Scroll Editor With Preview
- Preview > Preview: Scroll Preview With Editor

However, neither the Editor scrolls with the Preview nor vice versa.

**Comment by searKing** [comment]
Hi, Preview[2.3.2] is updated to use the Markdown API, Now auto scroll is supported.
