### ISSUE TITLE
Unable to build

### ISSUE THREAD

**Issue by KernelDeimos** [searKing/preview-vscode#75]
```
npm ERR! code EBADPLATFORM
npm ERR! notsup Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin"} (current: {"os":"linux","arch":"x64"})
npm ERR! notsup Valid OS:    darwin
npm ERR! notsup Valid Arch:  undefined
npm ERR! notsup Actual OS:   linux
npm ERR! notsup Actual Arch: x64
```

**Comment by KernelDeimos** [comment]
using `npm install -f` fixes this, now I get a new error
```
Error: Cannot find module '/home/edube/repos/puter-vscode/vscode_extensions/preview-vscode/node_modules/vscode/bin/install'
```

**Comment by KernelDeimos** [comment]
Using `npm install -f` fixes it, now I get...

```
Error: Cannot find module '<censored>/preview-vscode/node_modules/vscode/bin/install'
```

**Comment by KernelDeimos** [comment]
That last one was my fault, seems to work now. The note about `fsevents` might be a good addition to README.md

**Comment by searKing** [comment]
Preview[2.3.2] is updated and rewrite totally to use the Markdown API with less dependencies, `fsevents@2.3.3` can be installed on `darwain` and works well.
<img width="934" alt="image" src="https://github.com/searKing/preview-vscode/assets/4208726/08b69daa-7131-4309-838c-9847b9c59c83">
