### ISSUE TITLE
Syntax error in v2.2.5, no support for inline style-assigning.

### ISSUE THREAD

**Issue by sjackson0109** [searKing/preview-vscode#79]
Looks like the short-hand notation for class-assignment doesn't work with the vscode preview plugin...

Code:

``` 
graph TD
    direction TB
    classDef subnet color:#000,fill:#fff,stroke:#F58536,stroke-width:2px,stroke-dasharray:6;

    subgraph public-us-east-1a["us-east-1a"]::subnet
       ec21["<img class='Icon' src='https://icon.icepanel.io/AWS/svg/Compute/EC2.svg' /> EC2a"]
    end
```

Error:
```
Parse error on line 5:
...ast-1a["us-east-1a"]::subnet           
-----------------------^
Expecting 'SEMI', 'NEWLINE', 'EOF', got 'COLON'
```

It's drawing this without the short-hand:
![image](https://github.com/searKing/preview-vscode/assets/38080190/45349ca5-a030-421e-80a0-b3d0239ce13f)

I am aware there are other ways of assigning styles, such as:
```
   class public-us-east-1a subnet;
```
Which looks like this:
![image](https://github.com/searKing/preview-vscode/assets/38080190/7235db94-1da9-45e0-bd60-06e8f6f881fa)

Of course... thats an entire line of code..... vs just 2x characters (:) and the name of the style pre-defined.

**Comment by searKing** [comment]
Preview use [mermaid](https://mermaid.live/) inside，so behaves the same.
