### ISSUE TITLE
Copy button on formatted code block

### ISSUE THREAD

**Issue by zenfiric** [searKing/preview-vscode#83]
It would be great to have the copy button on the code blocks like on GitHub:

![image](https://github.com/searKing/preview-vscode/assets/5294258/97b84e14-1881-4c67-b195-7b816c8d2d04)

**Comment by searKing** [comment]
copy button for fence and code_block is supported in Preview prerelease version [2.3.4].
<img width="1266" alt="image" src="https://github.com/searKing/preview-vscode/assets/4208726/442a0793-1ab9-4813-9ead-d2d42e549061">
