### ISSUE TITLE
Change keybind for toggle preview in Linux

### ISSUE THREAD

**Issue by swiipius** [searKing/preview-vscode#85]
Hello, 

I'm running this extension on ubuntu 22.04. Because the key is ctrl+shift+v I can no longer paste in my zsh terminal. Is there a way to change this key ?

Thank you !

**Comment by searKing** [comment]
> Hello,
> 
> I'm running this extension on ubuntu 22.04. Because the key is ctrl+shift+v I can no longer paste in my zsh terminal. Is there a way to change this key ?
> 
> Thank you !

+ Nice advice! Update to `Preview@2.3.6` please, keybindings is limited to when `editorTextFocus || (explorerViewletVisible && filesExplorerFocus)`.

+ For early versions (<=2.3.5), You can change or delete the key in [Keyboard Shortcuts editor](https://code.visualstudio.com/docs/getstarted/keybindings#_keyboard-shortcuts-editor).
default keybindings "shift+cmd+v" for mac and "shift+ctrl+v" for else.
<img width="1191" alt="image" src="https://github.com/searKing/preview-vscode/assets/4208726/8e64f16f-a97e-4315-811d-9780330e5dbd">
