### ISSUE TITLE
ctrl+shift+v conflict with integrated terminal

### ISSUE THREAD

**Issue by guillermogoyanesbrooktec** [searKing/preview-vscode#86]
ctrl+shift+v is the keybinding to paste on the Linux terminal, so currently this plugin breaks this capacity by default.

**Comment by searKing** [comment]
Duplicates #85 , update to `Preview@2.3.6` please, keybindings is limited to when `editorTextFocus || (explorerViewletVisible && filesExplorerFocus)`.
