### ISSUE TITLE
Allow disabling indented code blocks.

### ISSUE THREAD

**Issue by RokeJulianLockhart** [searKing/preview-vscode#96]
Please see https://github.com/microsoft/vscode/issues/234485#issue-2686563242.

**Comment by searKing** [comment]
`Allow disabling indented code blocks` is supported in Preview version [2.3.8].

+ `indented code blocks` is enabled as default, you should disable it by `markdown.indented-code.enabled = false`
<img width="792" alt="Clipboard_Screenshot_1732731823" src="https://github.com/user-attachments/assets/1b43c525-6001-452a-968f-11415c0e1baf">

+ test case
```
<tr>
    <th>
        Construction
    </th>
    <td>

        ```PS1
        ${'Status'} = [PSCustomObject]@{
            'Non-Chronological' = 'Indeterminate';
            'Chronological' = [PSCustomObject]@{
                1 = @(
                    'Uncommenced',
                    'Commenced'
                );
                2 = @(
                    'Completed',
                    'Cancelled'
                )
            }
        }

        ${'Person'} = [PSCustomObject]@{
            3 = '';
            1 = '';
            2 = ''
        }
        ```
        
    </td>
</tr>
```
+ test result
<img width="1363" alt="Clipboard_Screenshot_1732731981" src="https://github.com/user-attachments/assets/c1f12100-7a19-4585-b20c-8607708cb075">

**Comment by RokeJulianLockhart** [comment]
> https://github.com/searKing/preview-vscode/issues/96#issuecomment-2504553232

That's superb, @searKing! Thank you. However, it doesn't appear to function quite correctly with slightly more complex Markdown:

https://github.com/user-attachments/assets/c8e841d4-ae71-42c0-b1e1-13ea69cbbaaf

**Comment by searKing** [comment]
+ Version [2.3.8] did not consider the difference between `TAB` and `SPACE`. Version [2.3.9] has addressed this issue and takes care of expanded tab. Please update to the [2.3.9] pre-release version.

+ test result
<img width="774" alt="Clipboard_Screenshot_1732774100" src="https://github.com/user-attachments/assets/cef68ad5-dbc2-404a-9aae-87a6c4e4dd3d">

**Comment by RokeJulianLockhart** [comment]
> https://github.com/searKing/preview-vscode/issues/96#issuecomment-2505340318

@searKing, that works perfectly! I can't explain how thankful I am. However, the syntax highlighting within the editor is now mostly non-functional. Is your extension able to remediate this, and if so, is this worth filing as a separate issue here?

**Comment by RokeJulianLockhart** [comment]
> https://github.com/searKing/preview-vscode/issues/96#issuecomment-2506276482

@searKing, apologies for being non-specific - I meant that the Markdown syntax highlighting does not remain (actually, for all *except* code blocks) when indented:

#### **Example (Screenshot)**

![@{'Type'='Screenshot'; 'Date'='+20241128T041135+0000'}#](https://github.com/user-attachments/assets/a00e8d41-f889-4df4-a506-907d4c36f614)

#### **Source (Markdown)**

```Markdown
<!DOCTYPE HTML>

	<!--
		<table>
			<tr>
				<th>
					Citation
				</th>
				<td>
					<a href="https://stackoverflow.com/revisions/9109157/2#:~:text=250-,In%20HTML%2C%20the,%3C!DoCtYpE%20hTmL%3E,-In%20XML%20serializations">
						Reference URI of aforementioned tag.
					</a>
				</td>
			</tr>
		</table>
	-->

<HTML lang="eng-GB-oxendict">

	<!--
		<table>
			<tr>
				<th>
					Citations
				</th>
				<td>
					<ol>
						<li>
							<a href="https://www.w3.org/International/questions/qa-html-language-declarations#nutshell:~:text=elements.%20For%20example:-,%3Chtml%20lang=%22en%22%3E,-Note%20that%20you">
								Reference URI of aforementioned tag's "<code>lang</code>" attribute.
							</a>
						</li>
						<li>
							<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1914627#c1:~:text=Specifically%2C%20eng%2DGB%20is,3166%2D1%20Alpha%203.">
								<code>bugzilla.mozilla.org/show_bug.cgi?id=1914627#c1</code>
							</a>
						</li>
					</ol>
				</td>
			</tr>
		</table>
	-->

	<!--
		<h2>
			Non-Rendered
		</h2>
	-->

		<head>

			<!--
				<h2>
					HTTP Attribute Declaration
				</h2>
			-->

			<meta
				http-equiv = "Content-Type"
				charset		= "UTF-8"
				content		= "text/HTML; charset=UTF-8"
			>

			<!--
				<table>
					<tr>
						<th>
							Citation
						</th>
						<td>
							<a href="https://stackoverflow.com/revisions/285036/5#:~:text=version%20of%20it):-,%3Cmeta%20charset=%22utf%2D8%22%3E,-That%20seems%20trivial%2C">
								<code>stackoverflow.com/posts/1346759</code>
							</a>
						</td>
					</tr>
				</table>
			-->

			<!--
				<h2>
					Title (Variable Declaration)
				</h2>
			-->

				<script type="text/JavaScript">
					let title = "Standards";
					document.title = title;
				</script>

				<title>
					<script type="text/JavaScript">
						document.write(title);
					</script>
				</title>

			<!--
				<h2>
					CSS
				</h2>
			-->

				<link
					type = "text/CSS"
					rel  = "stylesheet"
					href = "/home/RokeJulianLockhart/Documents/test/@%7B'Name'='Content'%3b%20Identifier='SLZS1K'%7D%23.dir/@%7B'Name'='Technical'%3b%20Identifier='SLZS47'%7D%23.dir/@%7B'Status'='Commenced'%3b%20'Name'='HTML%20Resources'%7D%23.dir/@%7B'Name'='CSS%203%20Stylesheet'%3b%20'Identifier'='SIFDYR'%7D%23.txt.CSS"
				>

					<!--
						<table>
							<tr>
								<th>
									Task
								</th>
								<td>
									Convert to relative path.
								</td>
							</tr>
							<tr>
								<th>
									Information
								</th>
								<td>
									<a href="https://poe.com/s/5yBzHp1KjTF9fOECbMDM#:~:text=Yes%2C%20relative%20paths,in%20the%20path.">
										<code>poe.com/s/5yBzHp1KjTF9fOECbMDM</code>
									</a>
								</td>
							</tr>
						</table>
					-->

				<!--
					<h2>
						Overrides
					</h2>
				-->

					<style>
						:root { --font-size: 10pt /* 1em */ !important; }
						:not(H1) { font-size: var(--font-size) !important; }
						H1 { font-size: calc(var(--font-size) * 1.5) !important; }
					</style>

		</head>

	<!--
		<h2>
			Variables
		</h2>
	-->

		<script type="text/JavaScript">
			let langPrefix	= "mis";			// <a href=""> Reference URI of aforementioned variable's value. </a>
			let classPrefix = "language"; // <a href=""> Reference URI of aforementioned variable's value. </a>
			let typePrefix	= "x";				// <a href=""> Reference URI of aforementioned variable's value. </a>
		</script>

	<!--
		<h2>
			Rendered
		</h2>
	-->

		<body>

			<h1>
				<script type="text/JavaScript">
					document.write(title);
				</script>
			</h1>

				<!--
					<h2>
						Content
					</h2>
				-->

					<p>
						IANA TZ database codes must be replaced by UN/LOCODE counterparts.
					</p>

					<ol>

						<li>
							<details open>
								<summary>
									<h2>
										Spectacle
									</h2>
								</summary>
								<div class="block-indent">

									<p>
										Unfortunately, when adding RFC 9557 tags, all calendar names are hardcoded.
									</p>

									<ol>

										<li>
											<details open>
												<summary>
													<h2>
														Screencast
													</h2>
												</summary>
												<div class="block-indent">

													```PS1
													@{'Type'='Screencast'; 'Date'='+<yyyy><MM><dd>T<hh><mm><ss><tt>'}#
													```

												</div>
											</details>
										</li>

										<li>
											<details open>
												<summary>
													<h2>
														Screenshot
													</h2>
												</summary>
												<div class="block-indent">

													```PS1
													@{'Type'='Screenshot'; 'Date'='+<yyyy><MM><dd>T<hh><mm><ss><tt>'}#
													```

												</div>
											</details>
										</li>

									</ol>

								</div>
							</details>
						</li>

						<li>
							<details open>
								<summary>
									<h2>
										<code>
											obs-studio
										</code>
									</h2>
								</summary>
								<div class="block-indent">

									```PS1
									@{'Type'='Screencast'; 'Date'='+%CCYY%MM%DDT%hh%mm%ss%z'}#
									```

									<p>
										I don't know how to add a timezone name to this.
									</p>

								</div>
							</details>
						</li>

						<li class="hidden">
							<details>
								<summary>
									<h2>
										Scripts
									</h2>
								</summary>
								<div class="block-indent">

									<div class="group">
										<script
											type = "text/JavaScript"
											src	= "file:///home/RokeJulianLockhart/Software/Git/GitLab.com/RokeJulianLockhart/sg5n9q/@%7B'Name'='Content'%3b%20Identifier='SLZS1K'%7D%23.dir/@%7B'Name'='Technical'%3b%20Identifier='SLZS47'%7D%23.dir/@%7B'Status'='Commenced'%3b%20'Name'='HTML%20Resources'%7D%23.dir/@%7B'Name'='ECMAScript%202023%20(ES14)%20Functionality'%3b%20'Identifier'='SISGH5'%7D%23.txt.JS#:~:text=%23!/usr/bin/env%20%2DS%20xdg%2Dopen,*/">
											// This is an external script. It is at the bottom of the file to ensure that loading it doesn't prevent the content which precedes it from being loaded.
										</script>
										
									</div>

								</div>
							</details>
						</li>

					</ol>

			</div>

		</body>

</HTML>
```

**Comment by searKing** [comment]
+ Grammar highlighting in indented code blocks is supported in pre-release version `Preview@2.3.10`. However, Preview primarily focuses on markdown rendering rather than grammar highlighting.

+ test result
<img width="857" alt="Clipboard_Screenshot_1733060246" src="https://github.com/user-attachments/assets/acb9c53f-20c3-496a-98d4-83b348518371">

**Comment by RokeJulianLockhart** [comment]
> https://github.com/searKing/preview-vscode/issues/96#issuecomment-2509774183

That's a massive improvement. The only things that still aren't rendered are:

1. HTML tag attributes on a new line (outside their tag declaration):

	<blockquote>

	~~~HTML
	<link
		type = "text/CSS"
		rel  = "stylesheet"
		href = "/home/RokeJulianLockhart/Documents/test/@%7B'Name'='Content'%3b%20Identifier='SLZS1K'%7D%23.dir/@%7B'Name'='Technical'%3b%20Identifier='SLZS47'%7D%23.dir/@%7B'Status'='Commenced'%3b%20'Name'='HTML%20Resources'%7D%23.dir/@%7B'Name'='CSS%203%20Stylesheet'%3b%20'Identifier'='SIFDYR'%7D%23.txt.CSS"
	>
	~~~

	</blockquote>

1.	CSS:

	<blockquote>

	~~~HTML
	<style>
		:root { --font-size: 10pt /* 1em */ !important; }
		:not(H1) { font-size: var(--font-size) !important; }
		H1 { font-size: calc(var(--font-size) * 1.5) !important; }
	</style>
	~~~

	</blockquote>

1. ECMAScript:

	<blockquote>

	~~~HTML
	<script type="text/JavaScript">
		let langPrefix	= "mis";			// <a href=""> Reference URI of aforementioned variable's value. </a>
		let classPrefix = "language"; // <a href=""> Reference URI of aforementioned variable's value. </a>
		let typePrefix	= "x";				// <a href=""> Reference URI of aforementioned variable's value. </a>
	</script>
	~~~

	</blockquote>

...if that's of use - I did see:

> Preview primarily focuses on markdown rendering rather than grammar highlighting.

**Comment by searKing** [comment]
+ `Syntax highlighting` has been reverted since `Preview@2.3.12` to focus solely on markdown `rendering`.
+ One way to support `syntax highlighting` is to create a separate [syntax-highlight extension](https://code.visualstudio.com/api/language-extensions/syntax-highlight-guide) with a modified [markdown.tmLanguage.json](https://github.com/microsoft/vscode/blob/main/extensions/markdown-basics/syntaxes/markdown.tmLanguage.json):
    - Replace: `[ ]{0,3}` with `[ ]{0,}`,  "heading" for example:
    
<img width="1007" alt="Clipboard_Screenshot_1733130802" src="https://github.com/user-attachments/assets/c93178a1-eeb5-4b7f-a53d-8b12e091b30f">

    - Remove the [raw_block](https://github.com/microsoft/vscode/blob/main/extensions/markdown-basics/syntaxes/markdown.tmLanguage.json#L2473C3-L2473C14) pattern
    
 <img width="756" alt="Clipboard_Screenshot_1733130673" src="https://github.com/user-attachments/assets/0aaa3f18-0e72-468b-962c-4a2aa02ba045">

**Comment by RokeJulianLockhart** [comment]
> Syntax highlighting has been reverted since `Preview@2.3.12` to focus solely on markdown rendering.

@searKing, can you elaborate on what you mean by this?

**Comment by searKing** [comment]
+ this [commit](https://github.com/searKing/preview-vscode/commit/30d583828c4e435a85d0cfeebfcb02d722c06738) is reverted, `syntax highlight` keeps the same as `Preview` is not installed.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/searKing/preview-vscode/issues/96#issuecomment-2511571658

@searKing, why? It seemed to me like a massive improvement.

**Comment by RokeJulianLockhart** [comment]
> - You're right, if disabling indented code blocks is supported, then syntax highlighting should be supported as well.
> - Grammar highlighting in indented code blocks is gracefully supported in pre-release version Preview@2.3.13.

@searKing, thank you. So much.

> I don't know why HTML elements in indented raw code blocks are not highlighted, but we can work around this issue by HTML elements placed in html|htm|shtml|xhtml|inc|tmpl|tpl fenced code blocks.

The problem is that they're *part* of the Markdown file, for Markdown permits inline HTML. They're being used just like in HTML - to link a CSS stylesheet to the file.

**Comment by searKing** [comment]
+ Grammar highlighting in indented code blocks is fully supported by the [built-in Markdown](https://github.com/microsoft/vscode/blob/main/extensions/markdown-basics/syntaxes/markdown.tmLanguage.json)  overwritten in the pre-release version Preview@2.3.14.
+ HTML elements in indented raw code blocks are highlighted now.

<img width="1078" alt="Clipboard_Screenshot_1733509898" src="https://github.com/user-attachments/assets/71c4cf8c-641a-4742-8940-8c2b0161eb90">
<img width="1028" alt="Clipboard_Screenshot_1733509914" src="https://github.com/user-attachments/assets/7b36d259-ec6f-4dfb-a508-436113ce94fb">

**Comment by RokeJulianLockhart** [comment]
> https://github.com/searKing/preview-vscode/issues/96#issuecomment-2523919423

@searKing, you're my saviour. I can't thank you enough. Is there somewhere I can donate?

**Comment by RokeJulianLockhart** [comment]
> https://github.com/searKing/preview-vscode/issues/96#issuecomment-2509774183

@searKing, one rather ironic problem remains. The syntax highlighting for Markdown itself still doesn't work with indented code blocks, like the undermentioned:

```Markdown
												~~~Markdown
												======================================
												  NetworkManager connection profiles
												======================================
												NAME                UUID                                  TYPE      DEVICE
												-------------------------------------------------------------------------------------------------------------------
												Wired connection 1  b78971c9-ff4d-3662-b9d7-68388de32248  ethernet  enp74s0
												TNCAPD0390D         077b03cf-982d-4544-8635-bec9e94e4557  wifi      wlp73s0
												lo                  e85a34e0-19ee-4830-9c3d-aaffa7d32156  loopback  lo
												~~~
```

However, it'll work for the undermentioned:

```Markdown
												~~~Markdown
======================================
  NetworkManager connection profiles
======================================
NAME                UUID                                  TYPE      DEVICE
-------------------------------------------------------------------------------------------------------------------
Wired connection 1  b78971c9-ff4d-3662-b9d7-68388de32248  ethernet  enp74s0
TNCAPD0390D         077b03cf-982d-4544-8635-bec9e94e4557  wifi      wlp73s0
lo                  e85a34e0-19ee-4830-9c3d-aaffa7d32156  loopback  lo
												~~~
```

Worth reporting separately?

**Comment by searKing** [comment]
+ The "heading-setext" was not highlighted because the built-in syntax highlighting rules required that === or --- must be at the beginning of the line, without any leading spaces. I have now relaxed this restriction, and you can upgrade to the Preview@2.3.15 pre-release version to experience the changes.
<img width="1136" alt="Clipboard_Screenshot_1733743084" src="https://github.com/user-attachments/assets/98fd06b5-71e5-481d-bd80-baa1ed9389e9">

+ "heading-setext" in indented raw code blocks are highlighted now.
<img width="1200" alt="Clipboard_Screenshot_1733743582" src="https://github.com/user-attachments/assets/c09ab3c9-ca44-4a79-856e-2fdafcae557f">

**Comment by gusbemacbe** [comment]
Good afternoon, @searKing!

Not just the list, the admonition syntax also is interpreted as an indented code block:

![On VSCode’s screenshot: code snippet showing a Markdown admonition block using ‘`!!! note`’ with an indented content inside an HTML section element.](https://github.com/user-attachments/assets/f9024ac8-2f08-44ac-b7e4-07f49240ac90)
